apiVersion: humanitec.io/v1alpha1
kind: Resource
metadata:
  annotations:
    app.humanitec.io/definition-id: default-humanitec-base-env
    app.humanitec.io/definition-version-id: 446c0fce-bef9-4048-ba5b-47e2edaf5903
    app.humanitec.io/deployment: 1852181e2388b973
    app.humanitec.io/env-type: gitops
    app.humanitec.io/matching-criteria-id: c72e691130b9c896
    app.humanitec.io/resource-class: default
  creationTimestamp: null
  labels:
    app.humanitec.io/app-id: testy
    app.humanitec.io/env-id: testy
    app.humanitec.io/org-id: clearcode
  name: resource-05cbebe27f9c6ca7ccd4a2f3288d654dfc212ab7
spec:
  configMapName: resource-configmap-05cbebe27f9c6ca7ccd4a2f3288d654dfc212ab7
  dependsOn: []
  driver: builtin://template
  driverInputs:
    driver:
      values: {}
    resource:
      id: /orgs/clearcode/apps/testy/envs/testy
  driverType: humanitec/template
  guresid: 05cbebe27f9c6ca7ccd4a2f3288d654dfc212ab7
  id: base-env
  secretName: resource-secret-05cbebe27f9c6ca7ccd4a2f3288d654dfc212ab7
  type: base-env
  workloadPatchName: resource-patch-05cbebe27f9c6ca7ccd4a2f3288d654dfc212ab7
status: {}
