apiVersion: humanitec.io/v1alpha1
kind: Resource
metadata:
  annotations:
    app.humanitec.io/definition-id: default-humanitec-workload-res
    app.humanitec.io/definition-version-id: 018b6a0c-91b8-43aa-b130-5114d0d71d45
    app.humanitec.io/deployment: 1852181e2388b973
    app.humanitec.io/env-type: gitops
    app.humanitec.io/matching-criteria-id: db70c377f7134da2
    app.humanitec.io/resource-class: default
  creationTimestamp: null
  labels:
    app.humanitec.io/app-id: testy
    app.humanitec.io/env-id: testy
    app.humanitec.io/org-id: clearcode
  name: resource-0a74846f9b96bdd40ad6c98ddf411cb92d72f4be
spec:
  configMapName: resource-configmap-0a74846f9b96bdd40ad6c98ddf411cb92d72f4be
  dependsOn:
  - resource-56e777a1b6687ce5e267dd2eafff9769480bd5c4
  - resource-dcdeddf5fa9891449c00cbf867a36afb05cd1e7d
  - resource-fb6eeb8834dffba7326cd288a4497788acdac7a6
  driver: builtin://template
  driverInputs:
    driver:
      values:
        templates:
          outputs: 'update: []'
    resource:
      dependencies:
      - ${resources["dns.default#modules.quickstart.externals.dns"].guresid}
      - ${resources["postgres.default#modules.quickstart.externals.db"].guresid}
      - ${resources["route.default#modules.quickstart.externals.route"].guresid}
      id: quickstart
      profile: humanitec/default-module
      spec:
        annotations:
          humanitec.io/managed-by: Score
          humanitec.io/workload-artefact-name: quickstart
        containers:
          hello-world:
            id: hello-world
            image: ghcr.io/astromechza/demo-app:latest
            variables:
              OVERRIDE_COLOR: '#ababab'
              OVERRIDE_POSTGRES: postgres://$\{externals.db.username}:$\{externals.db.password}@$\{externals.db.host}:$\{externals.db.port}/$\{externals.db.name}
        service:
          ports:
            www:
              container_port: 8080
              protocol: TCP
              service_port: 8080
  driverType: humanitec/template
  guresid: 0a74846f9b96bdd40ad6c98ddf411cb92d72f4be
  id: modules.quickstart
  secretName: resource-secret-0a74846f9b96bdd40ad6c98ddf411cb92d72f4be
  type: workload
  workloadPatchName: resource-patch-0a74846f9b96bdd40ad6c98ddf411cb92d72f4be
status: {}
